version: '1.0'

services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: toaipostgres
  app:
    container_name: app
    image: api-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/opt/project
    working_dir: /opt/project
    tty: true